# The IPv4 or IPv6 address and port to bind to
address = "127.0.0.1:8080"

# The base-64 encoded secret key used for deriving other cryptographic keys, such as a signing key for cookies
secret_key = ""
# The authentication mode used - Anonymous, Single, or Multi
# Anonymous disable authentication and login entirely. Any articles that require an authenticated account to access cannot
# be accessed. Creating articles is only possible if create_access is "Anonymous"
auth_mode = "Single"

# Specifies who is allowed to create new articles. Anonymous is not recommended, unless smolwik is secured otherwise.
# Anonymous, Authenticated, Accounts(),
create_access = "Authenticated"

# Specifies who can administer. Administrators can create other accounts.
administrator_access = { Accounts = ["demo"] }

# The file system directories to use for articles, assets, and templates relative to the current directory.
# The directory where the markdown files representing each article are saved. smolwik must be able to write, modify, and
# create new files and directories in this directory.
articles = "articles/"
# The directory where static assets like stylesheets and scripts are stored. smolwik only requires read access.
assets = "assets/"
# The glob to find page templates. smolwik only requires read access when starting up.
templates = "templates/**/*"
