name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download dependencies
      run: cargo fetch --verbose --locked
    - name: Check
      run: cargo check --verbose --frozen
    - name: Build (debug, glibc)
      run: cargo build --verbose --frozen
    - name: Build (release, glibc)
      run: cargo build --release --verbose --frozen
    - name: Build (debug, musl)
      run: cargo build --verbose --frozen --target x86_64-unknown-linux-musl
    - name: Build (release, musl)
      run: cargo build --release --verbose --frozen --target x86_64-unknown-linux-musl
    - name: Run tests (debug, glibc)
      run: cargo test --verbose --frozen
    - name: Run tests (release, glibc)
      run: cargo build --release --verbose --frozen
    - name: Run tests (debug, musl)
      run: cargo test --verbose --frozen --target x86_64-unknown-linux-musl
    - name: Run tests (release, musl)
      run: cargo build --release --verbose --frozen --target x86_64-unknown-linux-musl
