name: Build Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build (debug)
      run: cargo build --verbose
    - name: Run tests (debug)
      run: cargo test --verbose

    - name: Build (release)
      run: cargo build --release --verbose
    - name: Run tests (release)
      run: cargo test --verbose --release

    - name: Package
      run: |
        mkdir -p artifacts/data
        cp -r articles assets config.toml accounts.toml artifacts/data
        cp target/release/smolwik artifacts
        zip -r data.zip artifacts/data

    - name: Upload
    - uses: actions/upload-artifact@v4
      with:
        name: smolwik-release
        path: artifacts/**
